# Generated by Django 2.2 on 2019-04-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
