# Generated by Django 2.2 on 2019-05-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debitototal',
            options={'verbose_name_plural': 'Debitos'},
        ),
        migrations.AddField(
            model_name='financeiro',
            name='empresa_debito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='empresa_lancamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Empresa'),
            preserve_default=False,
        ),
    ]
