# Generated by Django 2.2 on 2019-05-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juridico',
        ),
    ]
