# Generated by Django 2.2 on 2019-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190424_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Dia do agendamento', verbose_name='Dia do agendamento')),
                ('hora_inicio', models.TimeField(help_text='Inicio do atendimento', verbose_name='Inicio do atendimento')),
                ('hora_termino', models.TimeField(help_text='fim do atendimento', verbose_name='fim do atendimento')),
                ('anotacoes', models.TextField(blank=True, help_text='Descrição', null=True, verbose_name='Descriçao')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamento',
            },
        ),
    ]
