# Generated by Django 2.2 on 2019-04-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agendamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={},
        ),
    ]
