# Generated by Django 2.2 on 2019-05-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190522_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=100)),
                ('cpf_reclamante', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cnpj_reclamado', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nome_advogado', models.CharField(max_length=100)),
                ('forum', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrada', models.DateField()),
                ('local_audiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_audiencia', models.DateField(blank=True, null=True)),
                ('sentenca', models.CharField(blank=True, max_length=100, null=True)),
                ('data_sentenca', models.DateField(blank=True, null=True)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('E', 'Entrada'), ('EA', 'Em andamento'), ('A', 'audiencia'), ('S', 'Sentença'), ('R', 'Recurso'), ('E', 'Execução')], default='E', max_length=2)),
                ('enviar_arquivo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('reclamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Empresa')),
                ('reclamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Associado')),
            ],
            options={
                'verbose_name_plural': 'Juridico',
            },
        ),
    ]
