# Generated by Django 2.2 on 2019-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190430_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora_termino',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='day',
            field=models.DateField(default='', help_text='Day of the event', verbose_name='Day of the event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='end_time',
            field=models.TimeField(default=1, help_text='Final time', verbose_name='Final time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='notes',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='start_time',
            field=models.TimeField(default=1, help_text='Starting time', verbose_name='Starting time'),
            preserve_default=False,
        ),
    ]
