# Generated by Django 2.2 on 2019-05-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_juridico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juridico',
            old_name='nome_advogado',
            new_name='advogado',
        ),
        migrations.RemoveField(
            model_name='juridico',
            name='data_sentenca',
        ),
        migrations.RemoveField(
            model_name='juridico',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='juridico',
            name='sentenca',
        ),
    ]
