# Generated by Django 2.2 on 2019-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190430_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='end_time',
            new_name='fim',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='notes',
            new_name='notas',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='day',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='start_time',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='dia',
            field=models.DateField(default=1, help_text='Dia', verbose_name='dia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='inicio',
            field=models.TimeField(default=1, help_text='termino', verbose_name='inicio'),
            preserve_default=False,
        ),
    ]
