# Generated by Django 2.2 on 2019-04-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190430_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
