# Generated by Django 2.2 on 2019-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juridico',
            options={'verbose_name_plural': 'Juridico'},
        ),
        migrations.AddField(
            model_name='juridico',
            name='enviar_arquivo',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
