# Generated by Django 2.2 on 2019-05-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_auto_20190519_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridico',
            name='cnpj_reclamado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='cpf_reclamante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='enviar_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='forum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
