# Generated by Django 2.2 on 2019-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_auto_20190519_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridico',
            name='motivo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
